/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardStaffRouteImport } from './routes/_auth/dashboard/staff'
import { Route as AuthDashboardSettingRouteImport } from './routes/_auth/dashboard/setting'
import { Route as AuthDashboardServiceRouteImport } from './routes/_auth/dashboard/service'
import { Route as AuthDashboardReservationRouteImport } from './routes/_auth/dashboard/reservation'
import { Route as AuthDashboardCustomersRouteImport } from './routes/_auth/dashboard/customers'
import { ServerRoute as ApiElectricTableServerRouteImport } from './routes/api/electric/$table'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardStaffRoute = AuthDashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardSettingRoute = AuthDashboardSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardServiceRoute = AuthDashboardServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardReservationRoute =
  AuthDashboardReservationRouteImport.update({
    id: '/reservation',
    path: '/reservation',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardCustomersRoute = AuthDashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const ApiElectricTableServerRoute = ApiElectricTableServerRouteImport.update({
  id: '/api/electric/$table',
  path: '/api/electric/$table',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/customers': typeof AuthDashboardCustomersRoute
  '/dashboard/reservation': typeof AuthDashboardReservationRoute
  '/dashboard/service': typeof AuthDashboardServiceRoute
  '/dashboard/setting': typeof AuthDashboardSettingRoute
  '/dashboard/staff': typeof AuthDashboardStaffRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard/customers': typeof AuthDashboardCustomersRoute
  '/dashboard/reservation': typeof AuthDashboardReservationRoute
  '/dashboard/service': typeof AuthDashboardServiceRoute
  '/dashboard/setting': typeof AuthDashboardSettingRoute
  '/dashboard/staff': typeof AuthDashboardStaffRoute
  '/dashboard': typeof AuthDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/customers': typeof AuthDashboardCustomersRoute
  '/_auth/dashboard/reservation': typeof AuthDashboardReservationRoute
  '/_auth/dashboard/service': typeof AuthDashboardServiceRoute
  '/_auth/dashboard/setting': typeof AuthDashboardSettingRoute
  '/_auth/dashboard/staff': typeof AuthDashboardStaffRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/reservation'
    | '/dashboard/service'
    | '/dashboard/setting'
    | '/dashboard/staff'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify'
    | '/dashboard/customers'
    | '/dashboard/reservation'
    | '/dashboard/service'
    | '/dashboard/setting'
    | '/dashboard/staff'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/verify'
    | '/_auth/dashboard'
    | '/_auth/dashboard/customers'
    | '/_auth/dashboard/reservation'
    | '/_auth/dashboard/service'
    | '/_auth/dashboard/setting'
    | '/_auth/dashboard/staff'
    | '/_auth/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/electric/$table': typeof ApiElectricTableServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/electric/$table': typeof ApiElectricTableServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/electric/$table': typeof ApiElectricTableServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/electric/$table'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/electric/$table'
  id: '__root__' | '/api/auth/$' | '/api/electric/$table'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiElectricTableServerRoute: typeof ApiElectricTableServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/staff': {
      id: '/_auth/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof AuthDashboardStaffRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/setting': {
      id: '/_auth/dashboard/setting'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof AuthDashboardSettingRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/service': {
      id: '/_auth/dashboard/service'
      path: '/service'
      fullPath: '/dashboard/service'
      preLoaderRoute: typeof AuthDashboardServiceRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/reservation': {
      id: '/_auth/dashboard/reservation'
      path: '/reservation'
      fullPath: '/dashboard/reservation'
      preLoaderRoute: typeof AuthDashboardReservationRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/customers': {
      id: '/_auth/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof AuthDashboardCustomersRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/electric/$table': {
      id: '/api/electric/$table'
      path: '/api/electric/$table'
      fullPath: '/api/electric/$table'
      preLoaderRoute: typeof ApiElectricTableServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthDashboardRouteChildren {
  AuthDashboardCustomersRoute: typeof AuthDashboardCustomersRoute
  AuthDashboardReservationRoute: typeof AuthDashboardReservationRoute
  AuthDashboardServiceRoute: typeof AuthDashboardServiceRoute
  AuthDashboardSettingRoute: typeof AuthDashboardSettingRoute
  AuthDashboardStaffRoute: typeof AuthDashboardStaffRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardCustomersRoute: AuthDashboardCustomersRoute,
  AuthDashboardReservationRoute: AuthDashboardReservationRoute,
  AuthDashboardServiceRoute: AuthDashboardServiceRoute,
  AuthDashboardSettingRoute: AuthDashboardSettingRoute,
  AuthDashboardStaffRoute: AuthDashboardStaffRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiElectricTableServerRoute: ApiElectricTableServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
